### ISSUE TITLE
Sometimes the history function don't work

### ISSUE THREAD

**Issue by stefanobasta** [cosmocode/dokuwiki-plugin-struct#241]
When I create the following assignment: '**' to use struct-variables for the whole dokuwiki database, some namespaces are blocked for the history view. 
In detail: When I try to open an old version of a page in a specific namespace, I see an empty page.
When I do it in another namespace (I think the difference is, that this namespace is already in the assignment list for other struct-variables) I can open old versions of pages.

**Comment by splitbrain** [comment]
What exactly is an empty page. Please see https://www.dokuwiki.org/faq:blankpage

**Comment by stefanobasta** [comment]
Message: "This is an old revision of the document!" (see attached screenshot)
![selection_007](https://cloud.githubusercontent.com/assets/15118725/20914674/7ef79740-bb81-11e6-970d-9c0012b98f9f.jpg)

**Comment by splitbrain** [comment]
is this all you see? then something is broken. please locate the appropriate log files and report any error messages you find.

**Comment by stefanfink** [comment]
Hopefully the attached file could help you
[debug.txt](https://github.com/cosmocode/dokuwiki-plugin-struct/files/636091/debug.txt)

**Comment by splitbrain** [comment]
No sorry. That's completely unrelated stuff. Please go back to the FAQ entry linked above and find the actual PHP error message.

**Comment by stefanfink** [comment]
Sorry, we have only access to these warning information (see below). We have no access to the error.log so I fear in this case I can't send you more information which can help you.
I can use your plug-in without addressing every page with "**". For me your plug-in is a very nice one.
Again sorry.


2016-12-08 09:53:44	Warning	109.205.3.1		mod_fcgid: stderr: PHP Fatal error: Uncaught exception 'dokuwiki\\plugin\\struct\\meta\\StructException' with message 'Schema does not exist. Only data of existing schemas can be accessed' in /var/www/vhosts/diasys-technologies.com/httpdocs/dokuwiki/lib/plugins/struct/meta/AccessTable.php:60, referer: http://diasys-technologies.com/dokuwiki/doku.php?id=r910_soft:current_versions&do=revisions				Erreur Apache
2016-12-08 09:53:44	Warning	109.205.3.1		mod_fcgid: stderr: Stack trace:, referer: http://diasys-technologies.com/dokuwiki/doku.php?id=r910_soft:current_versions&do=revisions				Erreur Apache
2016-12-08 09:53:44	Warning	109.205.3.1		mod_fcgid: stderr: #0 /var/www/vhosts/diasys-technologies.com/httpdocs/dokuwiki/lib/plugins/struct/meta/AccessTableData.php(22): dokuwiki\\plugin\\struct\\meta\\AccessTable->__construct(Object(dokuwiki\\plugin\\struct\\meta\\Schema), 'r910_soft:curre...', 1479728318), referer: http://diasys-technologies.com/dokuwiki/doku.php?id=r910_soft:current_versions&do=revisions				Erreur Apache
2016-12-08 09:53:44	Warning	109.205.3.1		mod_fcgid: stderr: #1 /var/www/vhosts/diasys-technologies.com/httpdocs/dokuwiki/lib/plugins/struct/meta/AccessTable.php(30): dokuwiki\\plugin\\struct\\meta\\AccessTableData->__construct(Object(dokuwiki\\plugin\\struct\\meta\\Schema), 'r910_soft:curre...', 1479728318), referer: http://diasys-technologies.com/dokuwiki/doku.php?id=r910_soft:current_versions&do=revisions				Erreur Apache
2016-12-08 09:53:44	Warning	109.205.3.1		mod_fcgid: stderr: #2 /var/www/vhosts/diasys-technologies.com/httpdocs/dokuwiki/lib/plugins/struct/meta/AccessTable.php(44): dokuwiki\\plugin\\struct\\meta\\AccessTable::bySchema(Object(dokuwiki\\plugin\\struct\\meta\\Schema), 'r910_soft:curre...', 1479728318), referer: http://diasys-technologies.com/dokuwiki/doku.php?id=r910_soft:current_versions&do=revisions				Erreur Apache
2016-12-08 09:53:44	Warning	109.205.3.1		mod_fcgid: stderr: #3 /var/www/vhosts/diasys-technologies.com in /var/www/vhosts/diasys-technologies.com/httpdocs/dokuwiki/lib/plugins/struct/meta/AccessTable.php on line 60, referer: http://diasys-technologies.com/dokuwiki/doku.php?id=r910_soft:current_versions&do=revisions				Erreur Apache

**Comment by splitbrain** [comment]
This is exactly the data I was asking for. Those are not warnings. It's a fatal error. We'll look into it.
