### ISSUE TITLE
"Table Alias already exists" error when trying to join data from two schemas

### ISSUE THREAD

**Issue by psy-q** [cosmocode/dokuwiki-plugin-struct#246]
We have two schemas "allgemein" (general) and "infrastruktur" (infrastructure), assigned like:

  * "allgemein" assigned to namespace `:**`
  * "infrastruktur" assigned to namespace `infrastruktur:**`

We'd like to use the fields for "allgemein" on all pages but "infrastruktur" only for pages describing infrastructure. Then it should be displayed as a table, so lists of infrastructure should display the categories of the pages. I tried it this way:

```
---- struct table ----
schema: infrastruktur, allgemein
select: %pageid%, %title%, infrastruktur.criticality, infrastruktur.depends-on, allgemein.category
headers: Name, Seitentitel, Kritikalität, Abhängigkeiten, Kategorie
----
```

But this doesn't work, I get the error "Table Alias already exists" and the following backtrace:

```
#0 /home/wiki/farm/farmer/lib/plugins/struct/meta/Search.php(377): dokuwiki\plugin\struct\meta\QueryBuilder->addLeftJoin('data_allgemein', 'multi_allgemein', 'M1', 'data_allgemein....')
#1 /home/wiki/farm/farmer/lib/plugins/struct/meta/Search.php(275): dokuwiki\plugin\struct\meta\Search->getSQL()
#2 /home/wiki/farm/farmer/lib/plugins/struct/meta/AggregationTable.php(83): dokuwiki\plugin\struct\meta\Search->execute()
#3 /home/wiki/farm/farmer/lib/plugins/struct/syntax/table.php(101): dokuwiki\plugin\struct\meta\AggregationTable->__construct('infrastruktur', 'xhtml', Object(Doku_Renderer_xhtml), Object(dokuwiki\plugin\struct\meta\SearchConfig))
#4 /home/wiki/farm/farmer/inc/parser/renderer.php(105): syntax_plugin_struct_table->render('xhtml', Object(Doku_Renderer_xhtml), Array)
#5 [internal function]: Doku_Renderer->plugin('struct_table', Array, 5, '---- struct tab...')
#6 /home/wiki/farm/farmer/inc/parserutils.php(652): call_user_func_array(Array, Array)
#7 /home/wiki/farm/farmer/inc/parserutils.php(128): p_render('xhtml', Array, NULL)
#8 /home/wiki/farm/farmer/inc/parserutils.php(81): p_cached_output('/home/wiki/wiki...', 'xhtml', 'infrastruktur')
#9 /home/wiki/farm/farmer/inc/html.php(281): p_wiki_xhtml('infrastruktur', 0, true, '')
#10 /home/wiki/farm/farmer/inc/template.php(106): html_show()
#11 /home/wiki/farm/farmer/inc/events.php(111): tpl_content_core('show')
#12 /home/wiki/farm/farmer/inc/events.php(238): Doku_Event->trigger('tpl_content_cor...', true)
#13 /home/wiki/farm/farmer/inc/template.php(83): trigger_event('TPL_ACT_RENDER', 'show', 'tpl_content_cor...')
#14 /home/wiki/farm/farmer/lib/tpl/dokuwiki/main.php(59): tpl_content()
#15 /home/wiki/farm/farmer/inc/actions.php(199): include('/home/wiki/farm...')
#16 /home/wiki/farm/farmer/doku.php(124): act_dispatch()
#17 {main}
```

Am I using this completely wrong? I thought I did it mostly according to the documentation but there must be something wrong.

Here are our [schemas](https://github.com/cosmocode/dokuwiki-plugin-struct/files/633951/schemas.zip).

**Comment by psy-q** [comment]
Holy crap, that was fast. Thanks! :tada:
