### ISSUE TITLE
Crash in bureaucracy form with page field in lookup and @FORMPAGE_ID@ placeholder

### ISSUE THREAD

**Issue by micgro42** [cosmocode/dokuwiki-plugin-struct#553]
## Steps to reproduce: 

1. create a lookup schema "foo" with a page field "page"
2. create a bureaucracy form to fill that schema with `@FORMPAGE_ID@` as placeholder :
```
<form>
action struct_lookup
struct_field "foo.page" "=@FORMPAGE_ID@"
submit "Add new call"
</form>
```
3. open the page with the form

## Expected results:
A form that allows me to fill that schema

## actual results:
![image](https://user-images.githubusercontent.com/7372507/105973963-a764fa00-608d-11eb-9b79-f2ee377eb2d3.png)

## stack trace:

```DTrace
2021-01-27 09:35:52dokuwiki\plugin\struct\meta\StructException: Lookup expects JSON /home/michael/public_html/dokuwiki/lib/plugins/struct/helper.php(194)
    #0 /home/michael/public_html/dokuwiki/lib/plugins/struct/types/Page.php(175): helper_plugin_struct::decodeJson('plugin:struct:e...')
    #0 /home/michael/public_html/dokuwiki/lib/plugins/struct/types/Page.php(175): helper_plugin_struct::decodeJson('plugin:struct:e...')
    #1 /home/michael/public_html/dokuwiki/lib/plugins/struct/meta/Value.php(128): dokuwiki\plugin\struct\types\Page->rawValue('plugin:struct:e...')
    #2 /home/michael/public_html/dokuwiki/lib/plugins/struct/meta/Value.php(42): dokuwiki\plugin\struct\meta\Value->setValue(Array)
    #3 /home/michael/public_html/dokuwiki/lib/plugins/struct/helper/field.php(99): dokuwiki\plugin\struct\meta\Value->__construct(Object(dokuwiki\plugin\struct\meta\Column), 'plugin:struct:e...')
    #4 /home/michael/public_html/dokuwiki/lib/plugins/bureaucracy/syntax.php(383): helper_plugin_struct_field->renderfield(Array, Object(Doku_Form), 1)
    #5 /home/michael/public_html/dokuwiki/lib/plugins/bureaucracy/syntax.php(226): syntax_plugin_bureaucracy->_htmlform(Array)
    #6 /home/michael/public_html/dokuwiki/inc/parser/renderer.php(117): syntax_plugin_bureaucracy->render('xhtml', Object(Doku_Renderer_xhtml), Array)
    #7 /home/michael/public_html/dokuwiki/inc/parserutils.php(673): Doku_Renderer->plugin('bureaucracy', Array, 5, '<form>\naction s...')
    #8 /home/michael/public_html/dokuwiki/inc/parserutils.php(142): p_render('xhtml', Array, NULL)
    #9 /home/michael/public_html/dokuwiki/inc/parserutils.php(89): p_cached_output('/home/michael/p...', 'xhtml', 'plugin:struct:e...')
    #10 /home/michael/public_html/dokuwiki/inc/Ui/PageView.php(68): p_wiki_xhtml('plugin:struct:e...', 0, true, '')
    #11 /home/michael/public_html/dokuwiki/inc/Action/Show.php(37): dokuwiki\Ui\PageView->show()
    #12 /home/michael/public_html/dokuwiki/inc/template.php(99): dokuwiki\Action\Show->tplContent()
    #13 [internal function]: tpl_content_core('show')
    #14 /home/michael/public_html/dokuwiki/inc/Extension/Event.php(133): call_user_func_array('tpl_content_cor...', Array)
    #15 /home/michael/public_html/dokuwiki/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger('tpl_content_cor...', true)
    #16 /home/michael/public_html/dokuwiki/inc/template.php(84): dokuwiki\Extension\Event::createAndTrigger('TPL_ACT_RENDER', 'show', 'tpl_content_cor...')
    #17 /home/michael/public_html/dokuwiki/lib/tpl/dokuwiki/main.php(58): tpl_content()
    #18 /home/michael/public_html/dokuwiki/inc/actions.php(27): include('/home/michael/p...')
    #19 /home/michael/public_html/dokuwiki/doku.php(122): act_dispatch()
    #20 {main} 
```

**Comment by annda** [comment]
After some debugging I found out that the form crashes only if you set `usetitles` to `true` in the config of your page field.

The changes introduced in 8050e34a30282b361887424ec59fd3636c2119f4 apparently did not make it into the bureaucracy field helper. 

The first fix that comes to mind would be to JSON encode the page fields in `\helper_plugin_struct_field::renderfield`. The tests run fine when I do that, but I'd rather investigate it a bit more before committing the code.
