### ISSUE TITLE
Cannot delete record - editing serial or global data

### ISSUE THREAD

**Issue by patrik123git** [cosmocode/dokuwiki-plugin-struct#659]
Hello,
when I try to delete a record in the struct serial or global editing interface with the "Delete entry" button in the "Actions" column (see images below), the record is not deleted in the DB; it disappears only in the currently opened view (after refreshing the page, the record is there again).
![image](https://github.com/cosmocode/dokuwiki-plugin-struct/assets/55781114/5f3a3120-db0a-456b-bbd7-f5044573a591)
![image](https://github.com/cosmocode/dokuwiki-plugin-struct/assets/55781114/8db23b74-9546-46c7-988e-0e4a75bd9e48)

DW version: 2023-04-04a "Jack Jackrum"
Struct plugin version: latest (2023-07-27)
sqlite plugin version: latest (2023-08-01)
I am using XAMPP with PHP 8.2.4 (I tried PHP 7.4.12 and the same error happened).

DW log:
```
PDOException: SQLSTATE[HY000]: General error: 1 near "?": syntax error
C:\xampp\htdocs\dokuwiki\lib\plugins\sqlite\SQLiteDB.php(133)
#0 C:\xampp\htdocs\dokuwiki\lib\plugins\struct\meta\AccessTableGlobal.php(28): dokuwiki\plugin\sqlite\SQLiteDB->query('DELETE FROM ? W...', 'data_schema1', 1)
#1 C:\xampp\htdocs\dokuwiki\lib\plugins\struct\action\aggregationeditor.php(111): dokuwiki\plugin\struct\meta\AccessTableGlobal->clearData()
#2 C:\xampp\htdocs\dokuwiki\lib\plugins\struct\action\aggregationeditor.php(82): action_plugin_struct_aggregationeditor->deleteRow()
#3 C:\xampp\htdocs\dokuwiki\inc\Extension\EventHandler.php(80): action_plugin_struct_aggregationeditor->handleAjax(Object(dokuwiki\Extension\Event), NULL)
#4 C:\xampp\htdocs\dokuwiki\inc\Extension\Event.php(74): dokuwiki\Extension\EventHandler->process_event(Object(dokuwiki\Extension\Event), 'BEFORE')
#5 C:\xampp\htdocs\dokuwiki\inc\Ajax.php(27): dokuwiki\Extension\Event->advise_before()
#6 C:\xampp\htdocs\dokuwiki\lib\exe\ajax.php(22): dokuwiki\Ajax->__construct('plugin_struct_a...')
#7 {main}
```

**Comment by moz0817** [comment]
I have exactly the same error. Versions like patrik123git but with php 7.4.

Adding a new record doesn't work for me either:
```php
PDOException: SQLSTATE[HY000]: General error: 8 attempt to write a readonly database
/mnt/offline/web/dwfarm/dokuwiki/lib/plugins/sqlite/SQLiteDB.php(143)
#0 /mnt/offline/web/dwfarm/dokuwiki/lib/plugins/sqlite/SQLiteDB.php(143): PDOStatement->execute()
#1 /mnt/offline/web/dwfarm/dokuwiki/lib/plugins/struct/meta/AccessTable.php(241): dokuwiki\plugin\sqlite\SQLiteDB->query()
#2 /mnt/offline/web/dwfarm/dokuwiki/lib/plugins/struct/meta/AccessDataValidator.php(121): dokuwiki\plugin\struct\meta\AccessTable->saveData()
#3 /mnt/offline/web/dwfarm/dokuwiki/lib/plugins/struct/helper.php(134): dokuwiki\plugin\struct\meta\AccessDataValidator->saveData()
#4 /mnt/offline/web/dwfarm/dokuwiki/lib/plugins/struct/action/aggregationeditor.php(130): helper_plugin_struct->saveLookupData()
#5 /mnt/offline/web/dwfarm/dokuwiki/lib/plugins/struct/action/aggregationeditor.php(78): action_plugin_struct_aggregationeditor->saveRow()
#6 /mnt/offline/web/dwfarm/dokuwiki/inc/Extension/EventHandler.php(80): action_plugin_struct_aggregationeditor->handleAjax()
#7 /mnt/offline/web/dwfarm/dokuwiki/inc/Extension/Event.php(74): dokuwiki\Extension\EventHandler->process_event()
#8 /mnt/offline/web/dwfarm/dokuwiki/inc/Ajax.php(27): dokuwiki\Extension\Event->advise_before()
#9 /mnt/offline/web/dwfarm/dokuwiki/lib/exe/ajax.php(22): dokuwiki\Ajax->__construct()
#10 {main}

```
