### ISSUE TITLE
Error after 2023-12-11 update

### ISSUE THREAD

**Issue by alexandrebastien** [cosmocode/dokuwiki-plugin-struct#699]
Here's the error:

```
Error loading plugin struct
ParseError: syntax error, unexpected 'fn' (T_STRING), expecting :: (T_PAAMAYIM_NEKUDOTAYIM)
More info is available in the error log.
```

**Comment by alexandrebastien** [comment]
And the complete log :

```
2023-12-12 19:25:24
ParseError: syntax error, unexpected 'fn' (T_STRING), expecting :: (T_PAAMAYIM_NEKUDOTAYIM)
/var/www/dokuwiki/lib/plugins/struct/action/migration.php(254)
#0 [internal function]: load_autoload('action_plugin_s...')
#1 [internal function]: spl_autoload_call('action_plugin_s...')
#2 /var/www/dokuwiki/inc/Extension/PluginController.php(107): class_exists('action_plugin_s...', true)
#3 /var/www/dokuwiki/inc/pluginutils.php(54): dokuwiki\Extension\PluginController->load('action', 'struct_migratio...', false, false)
#4 /var/www/dokuwiki/inc/Extension/EventHandler.php(32): plugin_load('action', 'struct_migratio...')
#5 /var/www/dokuwiki/inc/init.php(224): dokuwiki\Extension\EventHandler->__construct()
#6 /var/www/dokuwiki/doku.php(36): require_once('/var/www/dokuwi...')
#7 {main}
```

**Comment by annda** [comment]
It looks like your wiki is running on an unsupported version of PHP (< 7.4). Is that right?

**Comment by alexandrebastien** [comment]
It’s 7.3.31… I don’t manage the server myself so I just realised this.
