### ISSUE TITLE
TypeError with FORMPAGE_* Placeholder

### ISSUE THREAD

**Issue by moz0817** [cosmocode/dokuwiki-plugin-struct#711]
### Issue Description

I use the placeholder **FORMPAGE_ID** in a **bureaucracy-form**. 
The error occurs when all of these conditions are true:

1. fieldtype **page**
2. **Multi-Input** active
3. **usetitles** active

The Errorlog says:
`TypeError: array_map(): Argument #2 ($array) must be of type array, string given
  #0 /mnt/cluster/www/dokuwiki_ref/dokuwiki/lib/plugins/struct/helper/field.php(172): array_map()
  #1 /mnt/cluster/www/dokuwiki_ref/dokuwiki/lib/plugins/struct/helper/field.php(100): helper_plugin_struct_field->createValue()
  #2 /mnt/cluster/www/dokuwiki_ref/dokuwiki/lib/plugins/bureaucracy/syntax.php(385): helper_plugin_struct_field->renderfield()
  #3 /mnt/cluster/www/dokuwiki_ref/dokuwiki/lib/plugins/bureaucracy/syntax.php(228): syntax_plugin_bureaucracy->_htmlform()
  #4 /mnt/cluster/www/dokuwiki_ref/dokuwiki/inc/parser/renderer.php(126): syntax_plugin_bureaucracy->render()
  #5 /mnt/cluster/www/dokuwiki_ref/dokuwiki/inc/parserutils.php(691): Doku_Renderer->plugin()
  #6 /mnt/cluster/www/dokuwiki_ref/dokuwiki/inc/parserutils.php(158): p_render()
  #7 /mnt/cluster/www/dokuwiki_ref/dokuwiki/inc/parserutils.php(97): p_cached_output()
  #8 /mnt/cluster/www/dokuwiki_ref/dokuwiki/inc/Ui/PageView.php(67): p_wiki_xhtml()
  #9 /mnt/cluster/www/dokuwiki_ref/dokuwiki/inc/Action/Show.php(40): dokuwiki\Ui\PageView->show()
  #10 /mnt/cluster/www/dokuwiki_ref/dokuwiki/inc/template.php(120): dokuwiki\Action\Show->tplContent()
  #11 [internal function]: tpl_content_core()
  #12 /mnt/cluster/www/dokuwiki_ref/dokuwiki/inc/Extension/Event.php(134): call_user_func_array()
  #13 /mnt/cluster/www/dokuwiki_ref/dokuwiki/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger()
  #14 /mnt/cluster/www/dokuwiki_ref/dokuwiki/inc/template.php(102): dokuwiki\Extension\Event::createAndTrigger()
  #15 /mnt/cluster/www/dokuwiki_ref/dokuwiki/lib/tpl/dokuwiki/main.php(60): tpl_content()
  #16 /mnt/cluster/www/dokuwiki_ref/dokuwiki/inc/actions.php(30): include('...')
  #17 /mnt/cluster/www/dokuwiki_ref/dokuwiki/doku.php(131): act_dispatch()
  #18 {main}
`

**Comment by moz0817** [comment]
Update August 2026.

In my opinion, the check for the 'page' type to see if 'usetitles' is enabled—which leads to the error—can be removed here. Wiki IDs are always used for input, after all; the 'usetitles' option essentially applies only to the output.
Here the cleaned version of function createValue() in helper/field.php


        // page fields might need to be JSON encoded (the distinction regarding usetitles can be omitted here)
        if ( $this->column->getType() instanceof Page ) {
            $preparedValue = json_encode([$preparedValue, null], JSON_THROW_ON_ERROR);
        }
        $value = new Value($this->column, $preparedValue);

**Comment by moz0817** [comment]
If anyone can confirm this, I would appreciate a corresponding pull request. I have no idea how to do that.
